-- 2022년 1월 도서판매  - 저자별, 카테고리별 매출액 
-- 저자 ID 오름차순, 카테고리 내림차순
WITH TEMP AS (
SELECT A.BOOK_ID, SUM(SALES)*PRICE AS TOTAL_SALES
FROM BOOK_SALES AS A JOIN BOOK AS B ON A.BOOK_ID = B.BOOK_ID
WHERE YEAR(SALES_DATE)=2022 AND MONTH(SALES_DATE)=1
GROUP BY A.BOOK_ID
)

SELECT C.AUTHOR_ID, C.AUTHOR_NAME, A.CATEGORY, SUM(B.TOTAL_SALES) AS TOTAL_SALES
FROM BOOK AS A JOIN TEMP AS B ON A.BOOK_ID = B.BOOK_ID
                JOIN AUTHOR AS C ON A.AUTHOR_ID = C.AUTHOR_ID
GROUP BY C.AUTHOR_ID, A.CATEGORY
ORDER BY C.AUTHOR_ID, A.CATEGORY DESC 