-- 상품을 구매한 회원수를 집계, 오름차순 정렬=>성별정보가 없으면 결과에서 제외
SELECT YEAR(SALES_DATE) AS YEAR, MONTH(SALES_DATE) AS MONTH, GENDER, COUNT(DISTINCT(A.USER_ID)) AS USERS
FROM USER_INFO AS A JOIN ONLINE_SALE AS B ON A.USER_ID=B.USER_ID
WHERE GENDER IS NOT NULL 
GROUP BY YEAR(SALES_DATE), MONTH(SALES_DATE), GENDER
ORDER BY YEAR(SALES_DATE), MONTH(SALES_DATE), GENDER