-- 우유, 요거트를 동시에 구입한 장바구니 아이디 조회
-- 아이디순으로 조회(UNION-거나...)
WITH TEMP AS (SELECT DISTINCT CART_ID	
FROM CART_PRODUCTS
WHERE NAME = "Yogurt"
UNION ALL
SELECT DISTINCT CART_ID	
FROM CART_PRODUCTS
WHERE NAME = "Milk" )

SELECT CART_ID
FROM TEMP
GROUP BY CART_ID
HAVING COUNT(*)>=2