-- 입양간 동물 중 보호기간이 가장 길었던 동물 2마리 아이디, 이름
-- 보호기간이 긴순

WITH TEMP AS (
SELECT A.ANIMAL_ID, A.NAME, DATEDIFF(B.DATETIME, A.DATETIME) AS DIFF
FROM ANIMAL_INS AS A JOIN ANIMAL_OUTS AS B ON A.ANIMAL_ID = B.ANIMAL_ID
ORDER BY DIFF DESC
LIMIT 2
)
SELECT ANIMAL_ID, NAME
FROM TEMP