-- 우유(Milk)와 요거트(Yogurt)를 동시에 구입?
SELECT DISTINCT CART_ID
FROM CART_PRODUCTS
WHERE CART_ID IN (SELECT CART_ID FROM CART_PRODUCTS WHERE NAME = 'Yogurt' or NAME = 'Milk' GROUP BY CART_ID HAVING COUNT(DISTINCT NAME)>=2)
GROUP BY CART_ID
ORDER BY CART_ID;
