-- ANIMAL_INS(들어온 동물), ANIMAL_OUTS(입양보낸 동물)
-- 보호소는 중성화X, 나갈당시는 중성화 ㅇ 
-- 아이디순으로 조회
SELECT A.ANIMAL_ID, A.ANIMAL_TYPE, A.NAME
FROM ANIMAL_INS AS A JOIN ANIMAL_OUTS AS B ON A.ANIMAL_ID=B.ANIMAL_ID
WHERE A.SEX_UPON_INTAKE LIKE "%Intact%" AND (B.SEX_UPON_OUTCOME LIKE "%Spayed%" OR B.SEX_UPON_OUTCOME LIKE "%Neutered%")
ORDER BY A.ANIMAL_ID