-- 0시부터 23시까지 시간대별로 입양이 몇건이나 발생했는지 조회
-- 시간대 순으로 정렬
WITH RECURSIVE TIME AS (
    SELECT 0 AS NUM
    UNION ALL
    SELECT NUM+1 FROM TIME WHERE NUM<23)

SELECT TIME.NUM AS HOUR, COUNT(ANIMAL_ID) AS COUNT
FROM ANIMAL_OUTS RIGHT JOIN TIME ON HOUR(DATETIME) = NUM
GROUP BY HOUR
ORDER BY HOUR

# -- 시간대별로 입양이 몇건이 발생했는지? 시간대 순으로 정렬
# WITH RECURSIVE CTE AS (
# SELECT 0 AS NUM
# UNION ALL
# SELECT NUM+1 FROM CTE WHERE NUM<23)

# SELECT CTE.NUM AS HOUR, COUNT(ANIMAL_ID)
# FROM ANIMAL_OUTS RIGHT JOIN CTE ON HOUR(ANIMAL_OUTS.DATETIME)=CTE.NUM
# GROUP BY HOUR
# ORDER BY HOUR