-- 들어올 당시에는 중성화 x , 나갈떄는 중성화 (spayed female, neutered male) 
-- 아이디순으로 조회
SELECT B.ANIMAL_ID, B.ANIMAL_TYPE, B.NAME
FROM ANIMAL_INS AS A JOIN ANIMAL_OUTS AS B ON A.ANIMAL_ID = B.ANIMAL_ID
WHERE A.SEX_UPON_INTAKE LIKE '%Intact%'
AND (B.SEX_UPON_OUTCOME LIKE "%Spayed%" OR B.SEX_UPON_OUTCOME LIKE "%Neutered%")
ORDER BY B.ANIMAL_ID