-- 서울에 위치한 / 리뷰평균점수 소수점 3번째자리에서 반올림 / 평균점수, 즐겨찾기 수 기준 내림차순
SELECT A.REST_ID, REST_NAME, FOOD_TYPE, FAVORITES, ADDRESS
, ROUND(AVG(REVIEW_SCORE),2) AS SCORE
FROM REST_INFO AS A JOIN REST_REVIEW AS B ON A.REST_ID=B.REST_ID
WHERE ADDRESS LIKE "서울%"
GROUP BY A.REST_ID
ORDER BY SCORE DESC, FAVORITES DESC;