-- 상반기주문정보: FIRST_HALF, 7월의 아이스크리 주문정보=JULY
-- 7월에는 같은 맛의 아이스크림을 다른 출하번호를 갖기도 함
SELECT B.FLAVOR
FROM (SELECT FLAVOR, SUM(TOTAL_ORDER) AS TOTAL_ORDER 
      FROM FIRST_HALF
      GROUP BY FLAVOR
     ) A JOIN 
     (SELECT FLAVOR, SUM(TOTAL_ORDER) AS TOTAL_ORDER
     FROM JULY
     GROUP BY FLAVOR) B ON A.FLAVOR=B.FLAVOR
ORDER BY (A.TOTAL_ORDER+B.TOTAL_ORDER) DESC LIMIT 3