-- 동물보호소 들어온정보, 입양보낸 정보
-- 들어왔는데, 입양에 없는 동물 중 가장 오래 있었던 동물 3마리
SELECT A.NAME, A.DATETIME
FROM ANIMAL_INS AS A LEFT JOIN ANIMAL_OUTS AS B ON A.ANIMAL_ID=B.ANIMAL_ID
WHERE B.ANIMAL_ID IS NULL
ORDER BY DATETIME LIMIT 3