-- 완료된 중고거래 금액이 70만원 이상인 사람의 회원ID,닉네임, 총거래금액, 총거래금액을 기준으로 오름차순
SELECT USER_ID, NICKNAME, SUM(PRICE) AS TOTAL_SALES
FROM USED_GOODS_BOARD AS A JOIN USED_GOODS_USER AS B ON A.WRITER_ID = B.USER_ID
WHERE A.STATUS = 'DONE'
# AND PRICE>=700000
GROUP BY USER_ID
HAVING SUM(PRICE)>=700000
ORDER BY SUM(PRICE)