-- 대여시작일이 22년 9월, 대여기간이 30일 이상이면 장기대여, 아님 단기대여
-- 대여기록 ID기준 내림차순
SELECT HISTORY_ID, CAR_ID, DATE_FORMAT(START_DATE,"%Y-%m-%d") AS START_DATE, DATE_FORMAT(END_DATE,"%Y-%m-%d") AS END_DATE, IF(DATEDIFF(END_DATE, START_DATE)+1>=30, "장기 대여", "단기 대여") AS RENT_TYPE
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE YEAR(START_DATE)=2022 AND MONTH(START_DATE)=9
ORDER BY HISTORY_ID DESC 