-- 입양간 기록은 있는데, 보호소에 들어온 기록 없는 동물 id,이름 
-- id 순으로 조회
SELECT B.ANIMAL_ID, B.NAME
FROM ANIMAL_INS AS A RIGHT JOIN ANIMAL_OUTS AS B ON A.ANIMAL_ID = B.ANIMAL_ID
WHERE B.ANIMAL_ID NOT IN (SELECT A.ANIMAL_ID
                         FROM ANIMAL_INS AS A JOIN ANIMAL_OUTS AS B ON A.ANIMAL_ID = B.ANIMAL_ID)
ORDER BY B.ANIMAL_ID