-- 리뷰를 가장 많이 작성한 회원 리뷰 조회
-- 리뷰 작성일을 기준으로 오름차순, 리뷰 작성일이 같다면 리뷰 텍스트를 기준으로 오름차  정렬
SELECT MEMBER_NAME, REVIEW_TEXT, DATE_FORMAT(REVIEW_DATE, "%Y-%m-%d") AS REVIEW_DATE
FROM MEMBER_PROFILE AS A JOIN REST_REVIEW AS B ON A.MEMBER_ID=B.MEMBER_ID
WHERE A.MEMBER_ID = (SELECT B.MEMBER_ID  
                     FROM REST_REVIEW AS B
                    GROUP BY B.MEMBER_ID
                    ORDER BY COUNT(*) DESC LIMIT 1)
ORDER BY REVIEW_DATE, REVIEW_TEXT