-- 코드를 입력하세요 : COUNT의 MAX값
SELECT a.MEMBER_NAME, b.REVIEW_TEXT, date_format(b.REVIEW_DATE,'%Y-%m-%d') as REVIEW_DATE
FROM MEMBER_PROFILE a JOIN REST_REVIEW b ON a.MEMBER_ID=b.MEMBER_ID
WHERE a.MEMBER_ID = (SELECT MEMBER_ID FROM REST_REVIEW 
                    GROUP BY MEMBER_ID
                    ORDER BY COUNT(*) DESC LIMIT 1 )
ORDER BY REVIEW_DATE, REVIEW_TEXT