-- 2021년에 가입한 회원 중 상품을 구매한 회원수 / 2021년에 가입한 전체 회원 수 -소수점2번째에서 반올림 
-- 년 월 별로 출력(group by) 
-- 년기준,월 오름차순

-- 2021년에 가입한 사람 테이블 구하기
WITH INFO AS (
SELECT USER_ID, JOINED
FROM USER_INFO
WHERE YEAR(JOINED)=2021)

-- USER_ID는 겹치는 경우 있음..DISTINCT필요
SELECT YEAR(SALES_DATE) AS YEAR, MONTH(SALES_DATE) AS MONTH, COUNT(DISTINCT(A.USER_ID)) AS PUCHASED_USERS, ROUND(COUNT(DISTINCT(A.USER_ID))/(SELECT COUNT(*) FROM INFO),1) AS PUCHASED_RATIO
FROM INFO AS A JOIN ONLINE_SALE AS B ON A.USER_ID = B.USER_ID
GROUP BY YEAR, MONTH
ORDER BY YEAR, MONTH