-- 2022년 10월 16일에 대여 중인 자동차인 경우 '대여중', '대여 가능'
SELECT CAR_ID, IF(SUM(IF(START_DATE <= '2022-10-16' AND END_DATE >= '2022-10-16', 1, 0))>0,"대여중", "대여 가능") AS AVAILABILITY
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
GROUP BY CAR_ID
ORDER BY CAR_ID DESC;

# -- 2022년 10월 16일에 대여 중인 자동차인 경우 '대여중', '대여 가능'
# SELECT CAR_ID
# FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
# ORDER BY CAR_ID