-- 2022년 10월 16일에 대여 중인 자동차인 경우 '대여중' (반납날짜일떄도) 아님 대여가능
-- 자동차id기준 내림차순
SELECT CAR_ID, 
IF(SUM(IF(START_DATE<="2022-10-16" AND END_DATE>="2022-10-16", 1,0))>=1, "대여중","대여 가능") AS AVAILABILITY
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
GROUP BY CAR_ID
ORDER BY CAR_ID DESC;

# SELECT CAR_ID, 
# IF(START_DATE<="2022-10-16" AND END_DATE>="2022-10-16", 1,0) AS AVAILABILITY, 
# START_DATE, END_DATE
# FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
# ORDER BY CAR_ID DESC;