-- 입양 못간 동물 중, 가장 오래 보호소에 있던 동물 3마리
-- 보호시작일 순 조회
SELECT A.NAME, A.DATETIME
FROM ANIMAL_INS AS A LEFT JOIN ANIMAL_OUTS AS B ON A.ANIMAL_ID = B.ANIMAL_ID
WHERE A.ANIMAL_ID NOT IN (SELECT ANIMAL_ID
                         FROM ANIMAL_OUTS)
ORDER BY DATETIME
LIMIT 3