-- 도서정보, 판매정보(2022년 1월), 카테고리별 도서 판매량을 합산, CATEGORY, TOTAL_SALES리스트 출력
SELECT CATEGORY, SUM(SALES) AS TOTAL_SALES
FROM BOOK AS A JOIN BOOK_SALES AS B ON A.BOOK_ID = B.BOOK_ID
WHERE YEAR(SALES_DATE)=2022 AND MONTH(SALES_DATE)=1
GROUP BY CATEGORY
ORDER BY CATEGORY