-- 상품코드 별 매출액(판매가 * 판매량) 합계, 매출액을 기준으로 내림차순 정렬, 상품코드 기준 오름차순
SELECT PRODUCT_CODE, SUM(A.PRICE*B.SALES_AMOUNT) AS SALES
# SELECT PRODUCT_CODE, B.SALES_AMOUNT
FROM PRODUCT AS A JOIN OFFLINE_SALE AS B ON A.PRODUCT_ID = B.PRODUCT_ID
GROUP BY PRODUCT_CODE
ORDER BY SALES DESC, PRODUCT_CODE;
# ORDER BY PRODUCT_CODE;