-- 자동차정보 / 대여기록 정보 / 기간별 할인정책 정보
-- 트럭인 자동차의 대여기록별로 대여금액을 구하기
-- 대여금액 기준 내림차순, 같으면 id를 기준 내림차순
SELECT C.HISTORY_ID, ROUND((C.DAILY_FEE*(100-IF(D.DISCOUNT_RATE IS NULL, 0, DISCOUNT_RATE))/100) * (DATEDIFF(END_DATE,START_DATE)+1)) AS FEE
FROM 
(SELECT B.HISTORY_ID, A.CAR_TYPE, A.DAILY_FEE, B.START_DATE, B.END_DATE, 
 CASE WHEN DATEDIFF(END_DATE, START_DATE)+1>=90 THEN "90일 이상"
 WHEN DATEDIFF(END_DATE, START_DATE)+1>=30 THEN "30일 이상"
 WHEN DATEDIFF(END_DATE, START_DATE)+1>=7 THEN "7일 이상"
 END AS DURATION
FROM CAR_RENTAL_COMPANY_CAR AS A 
JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY AS B ON A.CAR_ID = B.CAR_ID 
WHERE A.CAR_TYPE='트럭') AS C
LEFT JOIN (
    SELECT DURATION_TYPE, DISCOUNT_RATE
    FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN
    WHERE CAR_TYPE='트럭') AS D
ON C.DURATION=D.DURATION_TYPE
ORDER BY FEE DESC, HISTORY_ID DESC;
