-- 자동차 종류 :트럭, 대여금액(FEE)을 구해서 대여기록 ID, 대여금액 리스트 출력
-- 대여금액 기준 내림차순, 대여기록 ID 내림차순
WITH DIFF AS (
SELECT HISTORY_ID, DAILY_FEE, CAR_TYPE, 
CASE WHEN DATEDIFF(END_DATE,START_DATE)+1>=90 THEN "90일 이상" 
WHEN DATEDIFF(END_DATE,START_DATE)+1>=30 THEN "30일 이상" 
WHEN DATEDIFF(END_DATE,START_DATE)+1>=7 THEN "7일 이상" END AS DURATION, DATEDIFF(END_DATE,START_DATE)+1 AS DD
FROM CAR_RENTAL_COMPANY_CAR AS A JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY AS B ON A.CAR_ID = B.CAR_ID
WHERE CAR_TYPE = "트럭"),

DISCOUNT AS (
SELECT CAR_TYPE, DURATION_TYPE, DISCOUNT_RATE
FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN 
WHERE CAR_TYPE = "트럭")

SELECT HISTORY_ID, ROUND(DAILY_FEE * (1-0.01*IF(DISCOUNT_RATE IS NULL, 0,DISCOUNT_RATE))*DD) AS FEE 
FROM DIFF LEFT JOIN DISCOUNT ON DIFF.DURATION = DISCOUNT.DURATION_TYPE
ORDER BY FEE DESC, HISTORY_ID DESC
