--  2022년 4월 13일 취소되지 않은(N) 흉부외과(CS) 진료 예약 내역을 조회
-- 진료예약일시를 기준으로 오름차순 정렬
SELECT A.APNT_NO, B.PT_NAME, B.PT_NO, C.MCDP_CD, C.DR_NAME, A.APNT_YMD
FROM APPOINTMENT AS A JOIN PATIENT AS B ON A.PT_NO = B.PT_NO 
JOIN DOCTOR AS C ON A.MDDR_ID = C.DR_ID
WHERE APNT_CNCL_YN = 'N'
AND DATE_FORMAT(APNT_YMD, "%Y-%m-%d") = "2022-04-13"
AND A.MCDP_CD = 'CS'
ORDER BY APNT_YMD 