WITH FE AS (
    SELECT *
    FROM SKILLCODES
    WHERE CATEGORY = 'Front End'
)

SELECT DISTINCT ID, EMAIL, FIRST_NAME, LAST_NAME
FROM DEVELOPERS A JOIN FE B ON A.SKILL_CODE & B.CODE
# &는 비트 AND연산자
ORDER BY ID