-- 완료된 중고거래의 총금액 70만원 이상 ->총거래금액 기준 오름차순
SELECT USER_ID, NICKNAME, SUM(PRICE) AS TOTAL_SALES
FROM USED_GOODS_USER AS A JOIN USED_GOODS_BOARD AS B ON A.USER_ID =B.WRITER_ID
WHERE B.STATUS = "DONE"
GROUP BY USER_ID
HAVING TOTAL_SALES>=700000
ORDER BY TOTAL_SALES
