-- 완료된 중고 거래 총금액 70만원 이상인 사람 / 게시판 정보 사용자정보
-- 총거래금액 기준 오름차순 찐찐, 보라보라, 크크큭, 후후후
WITH TEMP AS (
SELECT SUM(PRICE) AS TOTAL_SALES, USER_ID, NICKNAME, STATUS
FROM USED_GOODS_BOARD AS A JOIN USED_GOODS_USER AS B ON A.WRITER_ID = B.USER_ID
WHERE STATUS LIKE 'DONE'
GROUP BY USER_ID
)
SELECT USER_ID, NICKNAME, TOTAL_SALES
FROM TEMP
WHERE TOTAL_SALES>=700000 
ORDER BY TOTAL_SALES

