-- 코드를 입력하세요
SELECT A.PRODUCT_ID, PRODUCT_NAME, A.PRICE*SUM(B.AMOUNT) AS TOTAL_SALES
FROM FOOD_PRODUCT AS A JOIN FOOD_ORDER AS B ON A.PRODUCT_ID=B.PRODUCT_ID
WHERE YEAR(PRODUCE_DATE)=2022 AND MONTH(PRODUCE_DATE)=05
GROUP BY PRODUCT_NAME
ORDER BY TOTAL_SALES DESC, A.PRODUCT_ID
