-- 생산일자가 2022년 5월인 식품들의 식품 ID, 식품 이름, 총매출을 조회, 총매출을 기준으로 내림차순 정렬해주시고 총매출이 같다면 식품 ID를 기준으로 오름차순 정렬
SELECT B.PRODUCT_ID, PRODUCT_NAME, A.PRICE*SUM(B.AMOUNT) AS TOTAL_SALES
FROM FOOD_PRODUCT AS A JOIN FOOD_ORDER AS B ON A.PRODUCT_ID = B.PRODUCT_ID
WHERE DATE_FORMAT(B.PRODUCE_DATE,'%Y-%m')='2022-05'
GROUP BY B.PRODUCT_ID
ORDER BY TOTAL_SALES DESC, B.PRODUCT_ID