-- 1. 대여 시작일을 기준으로, 2022년 8월부터 2022년 10월까지 총 대여 횟수가 5회 이상(group by로 묶을 수 없다..)
-- 2. 해당 기간 동안 월별 자동차ID별 대여횟수 (0일 경우는 결과에서 제외)
-- 월 오름차순, 자동차ID내림차순
SELECT MONTH(START_DATE) AS MONTH, CAR_ID, COUNT(*) AS RECORDS
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE START_DATE>="2022-08-01" AND START_DATE<"2022-11-01"
AND CAR_ID IN (SELECT CAR_ID
              FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
              WHERE  START_DATE>="2022-08-01" AND START_DATE<"2022-11-01"
              GROUP BY CAR_ID
              HAVING COUNT(CAR_ID)>=5)
GROUP BY MONTH, CAR_ID
ORDER BY MONTH, CAR_ID DESC;