-- 자동차 종류 '세단' , 10월에 대여 시작한 기록이 있는id리스트(중복없이), id기준 내림차순
SELECT DISTINCT(A.CAR_ID) 
FROM CAR_RENTAL_COMPANY_CAR AS A JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY AS B ON A.CAR_ID = B.CAR_ID
WHERE CAR_TYPE = "세단" AND MONTH(B.START_DATE) = 10
ORDER BY A.CAR_ID DESC