-- 세단, SUV 자동차 중, 2022년 11월 1일부터 2022년 11월 30일까지 대여 가능
--  30일간의 대여 금액이 50만원 이상 200만원 미만인 자동차
-- 대여금액 기준 내림차순, 자동차종류 오름, 자동차ID 내림
WITH NOT_RENT AS (
    SELECT CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY 
    WHERE START_DATE<"2022-12-01" AND END_DATE>"2022-11-01"
),
CATEGORY AS (SELECT CAR_ID, CAR_TYPE, DAILY_FEE
FROM CAR_RENTAL_COMPANY_CAR
WHERE CAR_ID NOT IN (SELECT CAR_ID FROM NOT_RENT) AND CAR_TYPE IN ("세단","SUV")
),
DISCOUNTED_PRICE AS (
SELECT DISTINCT(CAR_ID), B.CAR_TYPE, ROUND((100-DISCOUNT_RATE)*0.01*30*DAILY_FEE,0) AS FEE
FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN AS A JOIN CATEGORY AS B ON A.CAR_TYPE=B.CAR_TYPE
WHERE DURATION_TYPE = '30일 이상'
)

SELECT CAR_ID, CAR_TYPE, FEE
FROM DISCOUNTED_PRICE
WHERE FEE>=500000 AND FEE<2000000
ORDER BY FEE DESC, CAR_TYPE, CAR_ID DESC
