-- 경제 카테고리에 속하는 도서의 ID,저자명, 출판일. 출판일 기준으로 오름차순
SELECT BOOK_ID, AUTHOR_NAME, DATE_FORMAT(PUBLISHED_DATE, '%Y-%m-%d') AS PUBLISHED_DATE
FROM BOOK AS A JOIN AUTHOR AS B ON A.AUTHOR_ID = B.AUTHOR_ID
WHERE A.CATEGORY="경제"
ORDER BY PUBLISHED_DATE;