-- 코드를 입력하세요 경제 CATEGORY의 도서ID, 저자명, 출판일을 출판일 기준 오름차순 정렬

SELECT BOOK_ID, AUTHOR_NAME, DATE_FORMAT(PUBLISHED_DATE, '%Y-%m-%d') as PUBLISHED_DATE
FROM BOOK JOIN AUTHOR ON BOOK.AUTHOR_ID = AUTHOR.AUTHOR_ID
WHERE CATEGORY='경제'
ORDER BY PUBLISHED_DATE
