-- 트럭, 대여기록별로 대여금액 구하기
-- 대여금액 기준 내림차순, 기록ID기준 내림차순
WITH TEMP AS (SELECT DATEDIFF(END_DATE, START_DATE)+1 AS DIFF, HISTORY_ID, A.CAR_ID, DAILY_FEE, 
              CASE WHEN DATEDIFF(END_DATE, START_DATE)+1>=90 THEN "90일 이상"
              WHEN DATEDIFF(END_DATE, START_DATE)+1>=30 THEN "30일 이상"
              WHEN DATEDIFF(END_DATE, START_DATE)+1>=7 THEN "7일 이상" END AS DURATION       
FROM CAR_RENTAL_COMPANY_CAR AS A JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY AS B ON A.CAR_ID = B.CAR_ID
WHERE CAR_TYPE = "트럭"),
P AS (
SELECT CAR_TYPE, DURATION_TYPE,DISCOUNT_RATE
FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN
WHERE  CAR_TYPE = "트럭")
SELECT HISTORY_ID, ROUND(DIFF*DAILY_FEE*(100-IF(DISCOUNT_RATE IS NULL, 0, DISCOUNT_RATE))*0.01,0) AS FEE
FROM TEMP AS A LEFT JOIN P AS B ON A.DURATION = B.DURATION_TYPE
ORDER BY FEE DESC, HISTORY_ID DESC 
