-- '세단'인 자동차들 중 10월에 대여를 시작한 기록이 있는 자동차 ID
--  중복이 없어야 하며, 자동차 ID를 기준으로 내림차순
SELECT DISTINCT B.CAR_ID
FROM CAR_RENTAL_COMPANY_CAR AS A JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY AS B ON A.CAR_ID=B.CAR_ID
WHERE CAR_TYPE='세단' AND MONTH(START_DATE)=10
ORDER BY CAR_ID DESC;
