--  조회수가 가장 높은 중고거래 게시물에 대한 첨부파일 경로를 조회
-- FILE ID를 기준으로 내림차순 정렬 /home/grep/src/BORAD_ID/FILE_ID + FILE_NAME .FILE_EXT
SELECT CONCAT("/home/grep/src/", A.BOARD_ID,"/", FILE_ID, FILE_NAME, FILE_EXT) FILE_PATH
FROM USED_GOODS_FILE AS A JOIN USED_GOODS_BOARD AS B ON A.BOARD_ID = B.BOARD_ID
WHERE VIEWS IN (SELECT MAX(VIEWS)
                  FROM USED_GOODS_BOARD)
ORDER BY FILE_ID DESC;
