-- 코드를 입력하세요 보호 시작일(DATETIME)>입양일(DATETIME)이 더 빠른 이름 조회 
SELECT B.ANIMAL_ID, B.NAME
FROM ANIMAL_INS AS A JOIN ANIMAL_OUTS AS B ON A.ANIMAL_ID = B.ANIMAL_ID
WHERE A.DATETIME >= B.DATETIME
ORDER BY A.DATETIME


